### ISSUE TITLE
exception handling in request function

### ISSUE THREAD

**Issue by SaraLuethi** [Meisterwerk-GmbH/bq-utils#10]
Mir ist grade im BqUtil etwas aufgefallen… im Bild ist die request-function:
Zeile 68…das “isset(json_decode($response, $jsonAssociative)->error)” --> muss da das jsonAssociative nicht raus und false rein? das muss doch immer false sein, damit man auf das error zugreifen kann
![image](https://user-images.githubusercontent.com/92802850/236843532-56fc98e9-8116-4626-8525-05cb8bc19c2d.png)

-> Timo: Du hast recht, du kannst das einfach weglassen dort. Der default Wert ist null == false…

**Comment by timble-one** [comment]
Bitte jeweils mit solchen Links arbeiten: https://github.com/Meisterwerk-GmbH/bq-utils/blob/6b094d1944f59060145b169b4d194ac07c88e6ed/src/BqUtil.php#L68. 
Du kannst dieser in Github erstellen, wenn du auf eine Zeile klickst...

**Comment by timble-one** [comment]
Passt, habe den PR approved 👍
