### ISSUE TITLE
RestManager erstellen

### ISSUE THREAD

**Issue by SaraLuethi** [Meisterwerk-GmbH/bq-utils#13]
Bitte auf dem BqUtils-Projekt einen Issue machen (und dir assignen), dass du dort einen RestManager erstellst, welchen du mit einem ApiKey und einem Pfad instanzieren kannst und der dann folgenden Funktionen hat:
- get
- put
- post
Dann soll in diesen Funktionen sowohl der API-Key automatisch gesetzt werden wie auch die entsprechenden Headers.

Danach baust du das zum testen in irgend einem Projekt ein.

https://github.com/Meisterwerk-GmbH/bq-post-print/pull/5#discussion_r1273654849

**Comment by SaraLuethi** [comment]
@71m024 was meinst du bei "mit einem Pfad instanzieren" mit Pfad? Nicht eine URL?

**Comment by timble-one** [comment]
Genau, das ist das Selbe.

**Comment by SaraLuethi** [comment]
@SaraLuethi noch in einem Projekt einbauen, gemergt ist es

**Comment by SaraLuethi** [comment]
@71m024 hast du ein bestimmtes Projekt im Kopf, wo ich das einbauen soll? Bisher ist es bereits im PR "PropertiesManager" eingebaut, und den baue ich dann wenn gemergt in bq-post-print ein.
