### ISSUE TITLE
Kleinigkeiten

### ISSUE THREAD

**Issue by timble-one** [Meisterwerk-GmbH/bq-utils#19]
- [x] auf php 8.2 umstellen
- [x] Variable `$phoneProperties` in `BqUtil:extractBqProperty` allgemeiner benennen.
- [x] extractBqProperty als deprecated markieren und umbenennen zu extractBqPropertyValue
- [x] neue Funktion schreiben die ein ganzes Property zurück gibt -> extractBqPropertyObject
- [x] `createOrUpdateProperty` umbenennen zu `createOrAppendStringProperty` (oder ähnlich). Die alte Funktion muss bestehen bleiben (WICHTIG) aber als deprecated markieren (mit einem Verweis auf die Neue Funktion.
   - Dann muss validiert werden, dass das Property, welches verändert oder erstellt wird auch wirklich ein string-property ist.
   - Am besten grad ein Enum für die verschiedenen Property-Types erstellen.

Wenn gemergt, kann man es einbauen in:
- bq-post-print
- shopify-booqable
- bq-bexio
- e-signatures
- bq-notifications
- bq-intrum (dort Funktion anders ein bisschen)
- --> überall

**Comment by timble-one** [comment]
@SaraLuethi  Wenn gemergt würde ich das vermutlich nur in einem Projekt zum testen updaten. Du kannst ja eines nehmen, wo das viel gebraucht wird (z.B. der print-client).  
Bei den anderen aktualisiert man ja dass dann automatisch irgendwann...

**Comment by SaraLuethi** [comment]
@71m024 Soll ich den Issue noch offen lassen, damit wir das Einbauen nicht vergessen, oder soll ich ihn closen?
