### ISSUE TITLE
Request-Function überarbeiten

### ISSUE THREAD

**Issue by SaraLuethi** [Meisterwerk-GmbH/bq-utils#5]
Default-Werte sinnvoll setzen. Nicht bei allen einzeln komisches Zeugs setzen. Wenn es wirklich gebraucht wird in der request-function einbauen, sonst überall rausnehmen im shopify-booqable

![Bildschirm­foto 2022-11-28 um 14 48 33](https://user-images.githubusercontent.com/92802850/204293547-d2448fea-2b99-450a-bc30-d46e5b28e433.png)

**Comment by SaraLuethi** [comment]
@71m024 also..brauchen tut es diese CURLOPT_xy nicht, es funktioniert ohne die meisten. aber was einige genau tun verstehe ich auch mit viel googeln nicht..
- CURLOPT_TIMEOUT braucht es definitiv nicht (weil default eh 0 ist)
- CURLOPT_POST braucht es auch nicht (weil automatisch bei postfields das mit gesetzt wird)
- CURLOPT_FOLLOWLOCATION und CURLOPT_MAXREDIRS gehören zusammen...weiss nicht ob es diese braucht , bzw. ob diese sinnvoll wären
- CURLOPT_ENCODING bin ich mir auch nicht sicher, denke eher nicht
- CURLOPT_HTTP_VERSION bin ich mir ebenfalls nicht sicher?
- CURLOPT_CUSTOMREQUEST würde ich tendenziell drin lassen, weil das ja sagt was es für ein Request ist oder nicht?

**Comment by timble-one** [comment]
- CURLOPT_TIMEOUT: Wie hast du herausgefunden, dass der default 0 ist??
- CURLOPT_FOLLOWLOCATION und CURLOPT_MAXREDIRS: Ich denke die sind mit `true` und `10` schon gut. Das bestimmt vermutlich ob einer Weiterleitung gefolgt wird und wie oft pro Request.  
- CURLOPT_ENCODING: Da würde ich als default Wert einfach einen leeren String setzen, weil das ja bis jetzt vermutlich an den meisten Orten so gemacht wird.  
- CURLOPT_HTTP_VERSION: Da würde ich als default das nehmen, was wir an den meisten Orten verwenden.  
- CURLOPT_CUSTOMREQUEST: Ich denke das muss der Aufrufer der Funktion selber setzen. Als default ist ziemlich sicher automatisch `GET` gesetzt. Von dem her musst du da wohl nichts machen.

**Comment by timble-one** [comment]
Lösche doch `CURLOPT_HTTP_VERSION` auch ganz raus. Würde es dort auch mal mit dem default Value versuchen.

**Comment by SaraLuethi** [comment]
@SaraLuethi 
- gibt den branch
- in 'test' getestet, aber noch testen mit der Verlinkung
- PR noch machen

**Comment by SaraLuethi** [comment]
- in bq-nuki und shopify-booqable einbinden

**Comment by SaraLuethi** [comment]
@71m024 ist in PR, muss es aber noch einbauen danach in bq-nuki und shopify-booqable
